# Generated by Django 4.2.7 on 2025-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default="'@student.auc.nl'", max_length=254),
        ),
    ]
