# Generated by Django 4.2.7 on 2025-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_university_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='university_college',
            field=models.CharField(choices=[('auc', 'Amsterdam University College'), ('luc', 'Leiden University College'), ('ucu', 'University College Utrecht'), ('ucr', 'University College Roosevelt'), ('ucm', 'University College Maastricht'), ('ucg', 'University College Groningen'), ('uct', 'University College Twente'), ('uctm', 'University College Tilburg Maastricht'), ('euc', 'Erasmus University College')], default='auc', max_length=4),
        ),
    ]
