# Generated by Django 4.2.7 on 2025-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_topic_university_college_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_university_college',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If True, this topic is visible to all university colleges'),
        ),
    ]
