# Generated by Django 4.2.7 on 2025-06-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_poll_polloption_post_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='poll',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='forum.poll'),
        ),
    ]
