# Generated by Django 4.2.7 on 2025-06-11 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    for topic in Topic.objects.all():
        if not topic.slug:
            topic.slug = slugify(topic.name)
            topic.save()

def reverse_populate_slugs(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    Topic.objects.all().update(slug=None)

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_poll_post_alter_post_author_alter_post_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='votes',
        ),
        migrations.AddField(
            model_name='polloption',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='users.customuser')),
            ],
            options={
                'unique_together': {('poll_option', 'user')},
            },
        ),
    ]
