# Generated by Django 4.2.7 on 2025-06-11 00:11

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    for topic in Topic.objects.all():
        if not topic.slug:
            base_slug = slugify(topic.name)
            slug = base_slug
            counter = 1
            # Ensure unique slug
            while Topic.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            topic.slug = slug
            topic.save()

def reverse_populate_slugs(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    Topic.objects.all().update(slug=None)

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_polloption_votes_polloption_vote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
