# Generated by Django 4.2.7 on 2025-03-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreply',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
